server:
  port: 5005
  runMode: debug
logger:
  filePath: ../logs/logs.log
  encoding: json
  level: debug
cors:
  allowOrigins: "*"
postgres:
  host:
  port:
  user:
  password:
  dbName:
  sslMode: false
redis:
  host:
  port:
  password:
  db: 0
  minIdleConnections: 100
  poolSize: 5000
  poolTimeout: 240
password:
  includeChars: true
  includeDigits: true
  minLength: 6
  maxLength: 64
  includeUppercase: true
  includeLowercase: true