server:
  internalPort: 5010
  externalPort: 5010
  runMode: release
logger:
  filePath: logs/
  encoding: json
  level: debug
  logger: zap
cors:
  allowOrigins: "*"
postgres:
  host:
  port:
  user:
  password:
  dbName:
  sslMode: disable
  maxIdleConnections: 15
  maxOpenConnections: 100
  connectionMaxLifetime: 5
redis:
  host:
  port:
  password:
  db: 0
  dialTimeout: 5
  writeTimeout: 5
  readTimeout: 5
  poolSize: 10
  poolTimeout: 15
  idleCheckFrequency: 500
  idleTimeout: 500
password:
  includeChars: true
  includeDigits: false
  minLength: 6
  maxLength: 64
  includeUppercase: false
  includeLowercase: false
otp:
  expireTime: 120
  digits: 6
  limiter: 10
jwt:
  secret: "mySecretKey"
  refreshSecret: "mySecretKey"
  accessTokenExpireDuration: 60
  refreshTokenExpireDuration: 60