server:
  internalPort: 5005
  externalPort: 5005
  runMode: debug
logger:
  filePath: ./logs/
  encoding: json
  level: debug
  logger: zap
cors:
  allowOrigins: "*"
postgres:
  host: localhost
  port: 5432
  user: postgres
  password: admin
  dbName: car_sale_db
  sslMode: disable
  maxIdleConnections: 15
  maxOpenConnections: 100
  connectionMaxLifetime: 5
redis:
  host: localhost
  port: 6379
  password: password
  db: 0
  dialTimeout: 5
  writeTimeout: 5
  readTimeout: 5
  poolSize: 10
  poolTimeout: 15
  idleCheckFrequency: 500
  idleTimeout: 500
password:
  includeChars: true
  includeDigits: false
  minLength: 6
  maxLength: 64
  includeUppercase: false
  includeLowercase: false
otp:
  expireTime: 120
  digits: 6
  limiter: 10
jwt:
  secret: "mySecretKey"
  refreshSecret: "mySecretKey"
  accessTokenExpireDuration: 60
  refreshTokenExpireDuration: 60